#!/bin/sh
# Execute inside test-workspace
cd $(dirname $0)

IEXEC_OUTV=$(pwd)/iexec_out
IEXEC_INV=$(pwd)/iexec_in

#rm -rf $IEXEC_OUTV
#mkdir -p $IEXEC_OUT

docker run --rm -e IEXEC_OUT=/iexec_out -e IEXEC_IN=/iexec_in -v $IEXEC_OUTV:/iexec_out -v $IEXEC_INV:/iexec_in --device /dev/isgx <username>/python-launcher-app:1.0.0 $@

echo
cat $IEXEC_OUTV/my-result.txt
